'\" t
.\"     Title: nvme-intel-get-max-lba
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 04/23/2020
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.TH "NVME\-INTEL\-GET\-MAX\-LBA" "1" "04/23/2020" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-intel-get-max-lba \- Send NVMe Get-Feature Command, returns feature ID (0xC1/0xC2)
.SH "SYNOPSIS"
.sp
.nf
\fInvme intel get\-max-lba\fR <device> [\-n | \-\-native\-lba]
.fi
.SH "DESCRIPTION"
.sp
Retrieves the NVMe get-feature (0xC1 / 0xC2 for native max lba)\&.
.sp
The <device> parameter is mandatory and may be either the NVMe character device (ex: /dev/nvme0), or a namespace block device (ex: /dev/nvme0n1)\&.
.sp
On success, the returned get-feature log may be returned as an unsigned integer. With the native flag [-n], the log may be returned as the native maximum lba.
.SH "OPTIONS"
.PP
\-n, \-\-native-lba
.RS 4
Print the native maximum LBA
.RE
.PP
\-j, \-\-json
.RS 4
Dump the output in json format 
.RE
.PP
\-r, \-\-raw
.RS 4
Dump the output in raw format
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Print the maximum LBA:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel get\-max\-lba /dev/nvme0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Print the maximum LBA:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel get\-max\-lba /dev/nvme0
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Print the native maximum LBA:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel get\-max\-lba /dev/nvme0 \-n
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Print in JSON format:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel get\-max\-lba /dev/nvme0 \-j
.fi
.if n \{\
.RE
.\}
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Print in Raw format:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel get\-max\-lba /dev/nvme0 \-r
.fi
.if n \{\
.RE
.\}
.RE
.RE
.sp
.SH "NVME"
.sp
Part of the nvme\-user suite
