'\" t
.\"     Title: nvme-intel-set-max-lba
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 04/23/2020
.\"    Manual: NVMe Manual
.\"    Source: NVMe
.\"  Language: English
.TH "NVME\-INTEL\-SET\-MAX\-LBA\" "1" "04/23/2020" "NVMe" "NVMe Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nvme-intel-set-max-lba \- Sends NVMe Set-Feature Command
.SH "SYNOPSIS"
.sp
.nf
\fInvme intel set\-max-lba\fR <device> [\-l | \-\-lba] [\-n | -\-namespace\-id]
.fi
.SH "DESCRIPTION"
.sp
Sends the NVMe set-feature (0xC1)\&.
.sp
The <device> parameter is mandatory and may be either the NVMe character device (ex: /dev/nvme0), or a namespace block device (ex: /dev/nvme0n1)\&.
.sp
On success, the feature log for maximum LBA (0xC1) may be changed depending on the specified namespace and the lba setting given. The namespace identifier, by default, will be set to 0.
.PP
.SH "OPTIONS"
\-l, \-\-lba
.RS 4
New LBA setting (required)
.RE
.PP
\-n, \-\-namespace\-id
.RS 4
Namespace identifier (optional)
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Set the maximum LBA:
.sp
.if n \{\
.RS 4
.\}
.nf
# nvme intel set\-max\-lba /dev/nvme0 \-\-namespace\-id=<NUM> \-\-lba=<NUM>
.fi
.SH "NVME"
.sp
Part of the nvme\-user suite
